# Register your lib to Unikraft's build system
$(eval $(call addlib_s,liblambda,$(CONFIG_LIBLAMBDA)))

# Add library source code to compilation
LIBLAMBDA_SRCS-y += $(LIBLAMBDA_BASE)/sqlite3.c
LIBLAMBDA_SRCS-y += $(LIBLAMBDA_BASE)/shell.c

# Extend the global include paths with library's folder
CINCLUDES-y += -I$(LIBLAMBDA_BASE)/include

LIBLAMBDA_FLAGS = -fdata-sections -ffunction-sections -fmerge-all-constants -fmerge-constants  -D_HAVE_SQLITE_CONFIG_H -DSQLITE_OMIT_LOAD_EXTENSION
LIBLAMBDA_FLAGS_SUPPRESS = -Wno-unused-parameter -Wno-unused-variable	\
-Wno-unused-but-set-variable -Wno-unused-value

LIBLAMBDA_CFLAGS-y +=  $(LIBLAMBDA_FLAGS)
LIBLAMBDA_CFLAGS-y +=  $(LIBLAMBDA_FLAGS_SUPPRESS)

LIBLAMBDA_CFLAGS-y += -Dmain=sqlite_main -Dwmain=sqlite_main